version: "2"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - /usr/projects/docker:/var/lib/postgresql
    ports:
      - "5432:5432"